### ISSUE TITLE
Deployment success but won't reflect on the dashboard.

### ISSUE THREAD

**Issue by glennposadas** [chat-sdk/chat-sdk-firebase#1]
The deployment in the CLI says ✔ Deploy complete!. But there's no update on the Firebase Functions Dashboard. I tried this multiple times already. In other project, I was able to deploy the functions that I have pretty easily.

<img width="441" alt="Screen Shot 2020-01-06 at 1 25 28 PM" src="https://user-images.githubusercontent.com/12502679/71797625-f5295180-3089-11ea-94d9-d6777c6812ee.png">

**Comment by bensmiley** [comment]
Hi @glennposadas To me it looks like the deployment was successful. Are you sure you're deploying it to the correct project?

**Comment by glennposadas** [comment]
Hi Ben,! Thanks for the fast reply! Yes, I'm 100% sure I'm using the correct project. There are only two projects associated in my account, so I can only be sure. Dev and Prod. I'm trying to deploy to Prod project.

I actually got successful deployment to Dev project before, and now I deleted the deployed functions in that project and now.... any deployment won't reflect too in that Dev project 😅

Maybe I'm forgetting something here.

**Comment by glennposadas** [comment]
Hi Ben, okay, I solved it! 

This instruction was kinda confusing for me:

> Find the functions directory you've just created and add the files: index.js and package.json from Github

I should store those two files inside that **functions** folder created for me. Lol. And npm install the missing module `npm install @google-cloud/logging`.

Voila! 

The output should be like this, for anyone experiencing confusion.

<img width="708" alt="Screen Shot 2020-01-07 at 1 51 22 PM" src="https://user-images.githubusercontent.com/12502679/71871721-130fb880-3155-11ea-8095-29b2a92463a2.png">
