### ISSUE TITLE
Facing issue when deploying to firebase using the terminal

### ISSUE THREAD

**Issue by deadpool9987** [chat-sdk/chat-sdk-firebase#6]
Hi 

I have followed your tutorial video step by step but I am getting issue at the point when i am about to deploy it to firebase console I have attached the screenshot of the issue 

<img width="897" alt="Screenshot 2021-01-28 at 2 23 23 AM" src="https://user-images.githubusercontent.com/35681183/106052952-39154b80-6110-11eb-96d2-a536f7dc865e.png">
 Please let me know i have been stuck at this point from past 2 days

**Comment by flywithnelson** [comment]
Have you had any luck with this? I was able to upload the firebase rules manually to firebase but I am unable to get push notifications to work due to the same error you are getting.

**Comment by Medic0353** [comment]
Have you had any luck with this? I was able to upload the firebase rules manually to firebase but I am unable to get push notifications to work due to the same error you are getting.
